name: "Service SemVer (Path-Aware)"
description: "Determine per-service semantic version bump based on commits that touched the service path"

inputs:
  service_name:
    description: "Service name (e.g. backend, frontend, receipt)"
    required: true
  service_path:
    description: "Path to service (e.g. services/backend)"
    required: true
  tag_prefix:
    description: "Tag prefix (e.g. backend-v)"
    required: true

outputs:
  bump_type:
    description: "none | patch | minor | major"
    value: ${{ steps.calc.outputs.bump }}
  base_version:
    description: "Computed base version (X.Y.Z)"
    value: ${{ steps.calc.outputs.base }}
  rc_tag:
    description: "Full RC tag (e.g. backend-v1.2.3-rc.7)"
    value: ${{ steps.calc.outputs.rc }}

runs:
  using: "composite"
  steps:
    - name: Calculate service version
      id: calc
      shell: bash
      run: |
        set -euo pipefail

        SERVICE_NAME="${{ inputs.service_name }}"
        SERVICE_PATH="${{ inputs.service_path }}"
        TAG_PREFIX="${{ inputs.tag_prefix }}"

        echo "Service: $SERVICE_NAME"
        echo "Path:    $SERVICE_PATH"
        echo "Prefix: $TAG_PREFIX"

        # Ensure we have full history and tags
        git fetch --tags --prune

        # -----------------------------
        # Find last service tag
        # -----------------------------
        LAST_TAG=$(git tag --list "${TAG_PREFIX}*" | sort -V | tail -n 1 || true)

        if [ -z "$LAST_TAG" ]; then
          echo "No previous tag found. Scanning all commits."
          RANGE=""
        else
          echo "Last tag: $LAST_TAG"
          RANGE="$LAST_TAG..HEAD"
        fi

        # -----------------------------
        # Determine bump type per service
        # -----------------------------
        BUMP="none"

        # Determine correct range for push vs PR
        if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
          RANGE="${GITHUB_BASE_SHA}..${GITHUB_SHA}"
        else
          if [ -z "$RANGE" ]; then
            RANGE="HEAD~50..HEAD"
          fi
        fi

        echo "Using range: $RANGE"
        COMMITS=$(git rev-list $RANGE)

        for COMMIT in $COMMITS; do
          # Use git show so merge commits are handled correctly
          FILES=$(git diff-tree --no-commit-id --name-only -r "$COMMIT" || true)

          if echo "$FILES" | grep -q "^$SERVICE_PATH/"; then
            MSG=$(git log -1 --pretty=%B "$COMMIT")

            if echo "$MSG" | grep -q "BREAKING CHANGE"; then
              BUMP="major"
              break
            elif echo "$MSG" | grep -q "^feat:"; then
              [ "$BUMP" != "major" ] && BUMP="minor"
            elif echo "$MSG" | grep -q "^fix:"; then
              [ "$BUMP" = "none" ] && BUMP="patch"
            fi
          fi
        done

        echo "Bump type: $BUMP"

        # -----------------------------
        # If no changes for this service
        # -----------------------------
        if [ "$BUMP" = "none" ]; then
          echo "bump=none" >> "$GITHUB_OUTPUT"
          echo "base=" >> "$GITHUB_OUTPUT"
          echo "rc=" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # -----------------------------
        # Calculate next version
        # -----------------------------
        if [ -z "$LAST_TAG" ]; then
          MAJOR=0
          MINOR=0
          PATCH=0
        else
          VERSION="${LAST_TAG#${TAG_PREFIX}}"
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          PATCH=$(echo "$VERSION" | cut -d. -f3)
        fi

        case "$BUMP" in
          major)
            MAJOR=$((MAJOR+1))
            MINOR=0
            PATCH=0
            ;;
          minor)
            MINOR=$((MINOR+1))
            PATCH=0
            ;;
          patch)
            PATCH=$((PATCH+1))
            ;;
        esac

        BASE="$MAJOR.$MINOR.$PATCH"
        RC="${TAG_PREFIX}${BASE}-rc.${GITHUB_RUN_NUMBER}"

        echo "Next version: $RC"

        echo "bump=$BUMP" >> "$GITHUB_OUTPUT"
        echo "base=$BASE" >> "$GITHUB_OUTPUT"
        echo "rc=$RC" >> "$GITHUB_OUTPUT"
