name: "Service SemVer (Path-Aware)"
description: "Determine per-service semantic version bump based on commits that touched the service path"

inputs:
  service_name:
    description: "Service name (e.g. backend, frontend, receipt)"
    required: true
  service_path:
    description: "Path to service (e.g. services/backend)"
    required: true
  tag_prefix:
    description: "Tag prefix (e.g. backend-v)"
    required: true
  additional_watch_paths:
    description: "Space-separated list of additional paths to watch for changes (triggers patch bump)"
    required: false
    default: ""

outputs:
  bump_type:
    description: "none | patch | minor | major"
    value: ${{ steps.calc.outputs.bump }}
  image_tag:
    description: "The calculated image tag (SHA for PRs, SemVer for Main)"
    value: ${{ steps.calc.outputs.image_tag }}
  base_version:
    description: "Computed base version (X.Y.Z) - Main only"
    value: ${{ steps.calc.outputs.base }}


runs:
  using: "composite"
  steps:
    - name: Calculate service version
      id: calc
      shell: bash
      run: |
        set -euo pipefail

        SERVICE_NAME="${{ inputs.service_name }}"
        SERVICE_PATH="${{ inputs.service_path }}"
        TAG_PREFIX="${{ inputs.tag_prefix }}"
        SEARCH_PREFIX="${SERVICE_NAME}-${TAG_PREFIX}"
        EXTRA_PATHS="${{ inputs.additional_watch_paths }}"

        echo "Service: $SERVICE_NAME"
        echo "Path:    $SERVICE_PATH"
        echo "Prefix: $TAG_PREFIX"
        echo "Search: $SEARCH_PREFIX"
        echo "Event: ${GITHUB_EVENT_NAME:-unknown}"

        # -----------------------------
        # PR MODE → SHA TAG
        # -----------------------------
        if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
          SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-7)
          TAG="${SHORT_SHA}"

          echo "PR mode detected. Tag: $TAG"
          echo "bump=pr" >> "$GITHUB_OUTPUT"
          echo "image_tag=$TAG" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # -----------------------------
        # MAIN MODE → SEMVER RC
        # -----------------------------
        git fetch --tags --prune --unshallow 2>/dev/null || true

        LAST_TAG=$(git tag --list "${SEARCH_PREFIX}*" | sort -V | tail -n 1 || true)

        if [ -z "$LAST_TAG" ]; then
          echo "No previous tag found."
          RANGE="HEAD~50..HEAD"
        else
          echo "Last tag: $LAST_TAG"
          RANGE="$LAST_TAG..HEAD"
        fi

        echo "Using range: $RANGE"
        COMMITS=$(git rev-list "$RANGE")

        BUMP="none"

        for COMMIT in $COMMITS; do
          MATCHED_SERVICE=false

          FILES=$(git show --pretty="" --name-only "$COMMIT" || true)

          if echo "$FILES" | grep -q "^$SERVICE_PATH/"; then
            MATCHED_SERVICE=true
          elif [ -n "$EXTRA_PATHS" ]; then
            for path in $EXTRA_PATHS; do
              if echo "$FILES" | grep -q "^$path"; then
                MATCHED_SERVICE=true
                break
              fi
            done
          fi

          if [ "$MATCHED_SERVICE" = "true" ]; then
            MSG=$(git log -1 --pretty=%B "$COMMIT")

            if echo "$MSG" | grep -q "BREAKING CHANGE"; then
              BUMP="major"
              break
            elif echo "$MSG" | grep -q "^feat:"; then
              [ "$BUMP" != "major" ] && BUMP="minor"
            elif echo "$MSG" | grep -q "^fix:"; then
              [ "$BUMP" = "none" ] && BUMP="patch"
            fi
          fi
        done

        echo "Bump type: $BUMP"

        if [ "$BUMP" = "none" ]; then
          echo "bump=none" >> "$GITHUB_OUTPUT"
          echo "image_tag=" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        if [ -z "$LAST_TAG" ]; then
          MAJOR=0; MINOR=0; PATCH=0
        else
          VERSION="${LAST_TAG#${SEARCH_PREFIX}}"
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          PATCH=$(echo "$VERSION" | cut -d. -f3)
        fi

        case "$BUMP" in
          major) MAJOR=$((MAJOR+1)); MINOR=0; PATCH=0 ;;
          minor) MINOR=$((MINOR+1)); PATCH=0 ;;
          patch) PATCH=$((PATCH+1)) ;;
        esac

        BASE="$MAJOR.$MINOR.$PATCH"
        RC="${TAG_PREFIX}${BASE}-rc.${GITHUB_RUN_NUMBER}"

        echo "Next version: $RC"
        echo "bump=$BUMP" >> "$GITHUB_OUTPUT"
        echo "base=$BASE" >> "$GITHUB_OUTPUT"
        echo "image_tag=$RC" >> "$GITHUB_OUTPUT"
